### ISSUE TITLE
The API Doesnt work ?

### ISSUE THREAD

**Issue by Raaptex** [nstrydom2/anonfile-api#49]
unsupported operand type(s) for -=: 'tuple' and 'int'
Traceback (most recent call last):
  File "c:\users\raptex\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\raptex\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\raptex\AppData\Local\Programs\Python\Python39\Scripts\anonfile.exe\__main__.py", line 7, in <module>
  File "c:\users\raptex\appdata\local\programs\python\python39\lib\site-packages\anonfile\__init__.py", line 37, in main
    print(f"URL: {upload.url.geturl()}")
AttributeError: 'NoneType' object has no attribute 'url'

**Comment by hentai-chan** [comment]
I can't reproduce this error with version `0.2.4`. Would have been great if you could use the `Bug Report` template next time you raise an issue. We need more information like example code used and your version of Python, etc.

**Comment by Raaptex** [comment]
> 
> 
> I can't reproduce this error with version `0.2.4`. Would have been great if you could use the `Bug Report` template next time you raise an issue. We need more information like example code used and your version of Python, etc.

Ok

**Comment by hentai-chan** [comment]
@Raaptex Update: the API currently only works with small (text) files, we didn't test larger input. We're currently working on a better solution and updating the docs.
